services:
  messenger.api:
    image: messenger.api
    build:
      context: ./Backend
      dockerfile: Messenger.API/Dockerfile
    networks:
      - net
    depends_on:
      messenger.db:
        condition: service_healthy
    
  messenger.db:
    image: postgres:15-alpine
    restart: always
    shm_size: 128mb
    secrets:
      - db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME} 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d messenger" ]
      interval: 30s
      timeout: 10s
      retries: 3
      
volumes:
  postgres_data:

networks:
  net:

secrets:
  db_password:
    file: ./secrets/db_password
